# Disable power to Wyze cameras when I am home
- alias: "Turn off security cameras when home"
  trigger:
    - platform: state
      entity_id: person.mitchell
      to: 'home'
  action:
    - service: switch.turn_off
      entity_id:
        - switch.living_room_wyze_power
        - switch.kitchen_cam
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.alexa_ha_bedroom_cam

- alias: "Turn on security cameras when away"
  trigger:
    - platform: state
      entity_id: person.mitchell
      from: 'home'
  action:
    - service: switch.turn_on
      entity_id:
        - switch.living_room_wyze_power
        - switch.kitchen_cam
    - service: input_boolean.turn_on
      entity_id:
        - input_boolean.alexa_ha_bedroom_cam

- alias: "Update USPS Mail Camera"
  trigger:
    - platform: state
      entity_id: sensor.mail_usps_mail

  action:
    - service: local_file.update_file_path
      data_template:
        entity_id: camera.mail_usps
        file_path: >
          {% if state_attr('sensor.mail_usps_mail','image') == None  %}
          /config/custom_components/mail_and_packages/mail_none.gif
          {% else %}
          /config/images/mail_and_packages/{{ state_attr('sensor.mail_usps_mail','image') }}
          {% endif %}

# From github.com/brianjking/homeassistant-config
- alias: "New Home Assistant Version Notifier"
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: 'off'
      to: 'on'
  action:
    - service: notify.mobile_app_mitchell_s_iphone
      data_template:
        message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }}  is now available."


- id: power_cycle_wled_daily
  alias: Power cycle WLED daily
  trigger:
  - platform: time
    at: 04:00:00
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: light.wled_dresser
      state: 'off'
    - condition: state
      entity_id: light.wled_bed
      state: 'off'
    - condition: state
      entity_id: light.wled_nightstand_left
      state: 'off'
    - condition: state
      entity_id: light.wled_nightstand_right
      state: 'off'
  - condition: or
    conditions:
    - condition: template
      value_template: '{{ ( as_timestamp(now()) - as_timestamp(state_attr(''automation.power_cycle_wled_daily'',
        ''last_triggered'')) |int(0) ) > 144000 }}'
  action:
  - service: rest_command.wled_bed_reboot
  - service: rest_command.wled_dresser_reboot
  - service: rest_command.wled_nightstand_left_reboot
  - service: rest_command.wled_nightstand_right_reboot
  mode: single
