# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
cloud:
stream:
system_health:

#frontend
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#lovelace:
#  mode: yaml

sensor: !include_dir_list sensors/
binary_sensor: !include_dir_merge_list binary_sensors/
camera: !include_dir_merge_list cameras/

switch: !include_dir_merge_list devices/switches/
light: !include_dir_merge_list devices/lights/

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api_key

habitica:
  - api_user: !secret HABITICA_USERNAME
    api_key: !secret HABITICA_API_KEY

rest_command: !include_dir_merge_named rest_command/
