# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
cloud:
stream:
system_health:
#pyscript:
#  allow_all_imports: true
#  hass_is_global: true

#frontend
#frontend:
#  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

#lovelace:
#  mode: yaml

#sensor: !include_dir_list sensors/
sensor: !include sensors.yaml
binary_sensor: !include_dir_merge_list binary_sensors/
camera: !include_dir_merge_list cameras/

switch: !include_dir_merge_list devices/switches/
light: !include_dir_merge_list devices/lights/

weather:
  - platform: openweathermap
    api_key: !secret openweathermap_api_key

habitica:
  - api_user: !secret HABITICA_USERNAME
    api_key: !secret HABITICA_API_KEY

rest_command: !include_dir_merge_named rest_command/

emulated_hue:
  expose_by_default: true
  exposed_domains:
    - light
  entities:
    light.balcony_string_lights:
      name: "Balcony String Lights"

nest:
  client_id: !secret NEST_CLIENT_ID
  client_secret: !secret NEST_CLIENT_SECRET
  # "Project ID" in the Device Access Console
  project_id: !secret NEST_PROJECT_ID
  # Provide the full path exactly as shown under "Subscription name" in Google Cloud Console
  subscriber_id: !secret NEST_SUBSCRIBER_ID
