- platform: waze_travel_time
  name: "Home to Campus"
  origin: zone.home
  destination: zone.science_drive_garage
  region: 'US'
  units: imperial

- platform: openweathermap
  api_key: !secret openweathermap_api_key
  forecast: true
  monitored_conditions:
    - weather 
