- platform: template
  sensors:
    alexa_ha_bedroom_cam:
      friendly_name: "Alexa HA - Bedroom Camera Switch"
      device_class: garage_door
      value_template: "{{ is_state('input_boolean.alexa_ha_bedroom_cam', 'on') }}"
