# From github.com/brianjking/homeassistant-config
- alias: "New Home Assistant Version Notifier"
  trigger:
    - platform: state
      entity_id: binary_sensor.updater
      from: 'off'
      to: 'on'
  action:
    - service: notify.mobile_app_mitchell_s_iphone
      data_template:
        message: "Home Assistant {{ state_attr('binary_sensor.updater', 'newest_version') }}  is now available."
