- alias: "Update USPS Mail Camera"
  trigger:
    - platform: state
      entity_id: sensor.mail_usps_mail

  action:
    - service: local_file.update_file_path
      data_template:
        entity_id: camera.mail_usps
        file_path: >
          {% if state_attr('sensor.mail_usps_mail','image') == None  %}
          /config/custom_components/mail_and_packages/mail_none.gif
          {% else %}
          /config/www/mail_and_packages/{{ state_attr('sensor.mail_usps_mail','image') }}
          {% endif %}
