# Disable power to Wyze cameras when I am home
- alias: "Turn off security cameras when home"
  trigger:
    - platform: state
      entity_id: person.mitchell
      to: 'home'
  action:
    - service: switch.turn_off
      entity_id: 
        - switch.living_room_wyze_power
        - switch.kitchen_cam
    - service: input_boolean.turn_off
      entity_id:
        - input_boolean.alexa_ha_bedroom_cam

- alias: "Turn on security cameras when away"
  trigger:
    - platform: state
      entity_id: person.mitchell
      from: 'home'
  action:
    - service: switch.turn_on
      entity_id:
        - switch.living_room_wyze_power
        - switch.kitchen_cam
    - service: input_boolean.turn_on
      entity_id:
        - input_boolean.alexa_ha_bedroom_cam
