- platform: ffmpeg
  name: Living Room Cam
  input: !secret living_room_camp

- platform: ffmpeg
  name: Bedroom Cam
  input: !secret bedroom_cam

- platform: ffmpeg
  name: Kitchen Cam
  input: !secret kitchen_cam

- platform: ffmpeg
  name: Percy Crate Cam
  input: !secret percy_crate_cam
